general.import = [
  "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
startup_mode = "Maximized" # options: "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
decorations = "Buttonless"

[font]
normal.family = "Hack Nerd Font"
size = 14
offset = { x = 0, y = 3 }

# [keyboard]
# Enter CopyMode with Command + Shift + V
# bindings = [{ "V", "Control|Shift", "ToggleViMode" },]

